
FROM mofa_env:latest

# 设置 OpenSSL 环境变量
ENV OPENSSL_VERSION=""
ENV OPENSSL_VERSION=3.3.2
ENV OPENSSL_INSTALL_DIR=/usr/local/openssl-${OPENSSL_VERSION}
ENV PATH=${OPENSSL_INSTALL_DIR}/bin:${PATH}
ENV LD_LIBRARY_PATH=${OPENSSL_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
ENV C_INCLUDE_PATH=${OPENSSL_INSTALL_DIR}/include:${C_INCLUDE_PATH}
ENV LIBRARY_PATH=${OPENSSL_INSTALL_DIR}/lib:${LIBRARY_PATH}
ENV PKG_CONFIG_PATH=${OPENSSL_INSTALL_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}



ENV OPENSSL_VERSION=3.3.2
ENV OPENSSL_INSTALL_DIR=/usr/local/openssl-${OPENSSL_VERSION}
ENV PATH=${OPENSSL_INSTALL_DIR}/bin:${PATH}
ENV LD_LIBRARY_PATH=${OPENSSL_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
ENV C_INCLUDE_PATH=${OPENSSL_INSTALL_DIR}/include:${C_INCLUDE_PATH}
ENV LIBRARY_PATH=${OPENSSL_INSTALL_DIR}/lib:${LIBRARY_PATH}
ENV PKG_CONFIG_PATH=${OPENSSL_INSTALL_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}

# 设置 Miniconda 安装的相关变量
ENV MINICONDA_VERSION=latest
ENV MINICONDA_INSTALLER=Miniconda3-$MINICONDA_VERSION-Linux-aarch64.sh
ENV MINICONDA_PREFIX=/opt/conda
ENV PATH=$MINICONDA_PREFIX/bin:$PATH

RUN yum update -y && \
    yum groupinstall -y "Development Tools" && \
    yum install -y \
        git \
        vim \
        cmake \
        uuid-devel \
        libuuid-devel \
        openssl-devel \
        python3-devel \
        make \
        wget \
        curl \
        curl-devel && \
    yum clean all 
RUN cd /project && \
    git clone https://github.com/xlang-foundation/xMind.git && \
    cd xMind/ThirdParty && \
    git clone https://github.com/xlang-foundation/xlang.git && \
    cd xlang && \
    echo "Switched to Jit branch successfully." && \
    cd /project/xMind && \
    mkdir -p out && \
    echo "Created build directory successfully."

RUN mkdir -p /usr/local/src && \
    cd /usr/local/src && \
    wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
    tar -xzvf openssl-${OPENSSL_VERSION}.tar.gz && \
    cd openssl-${OPENSSL_VERSION} && \
    ./config --prefix=${OPENSSL_INSTALL_DIR} --openssldir=${OPENSSL_INSTALL_DIR} shared zlib && \
    make -j$(nproc) && \
    make install && \
    # 备份现有的 OpenSSL 并链接新的版本
    mv /usr/bin/openssl /usr/bin/openssl.bak && \
    ln -s ${OPENSSL_INSTALL_DIR}/bin/openssl /usr/bin/openssl && \
    # 配置动态链接器以包含新的 OpenSSL 库 \
    echo 'export PATH="${OPENSSL_PREFIX}/bin:$PATH"' >> ~/.bashrc && \
    echo 'export LD_LIBRARY_PATH="${OPENSSL_PREFIX}/lib:$LD_LIBRARY_PATH"' >> ~/.bashrc && \
    echo "${OPENSSL_INSTALL_DIR}/lib" > /etc/ld.so.conf.d/openssl-3.3.2.conf && \
    ldconfig && \
    # 清理 OpenSSL 源码文件以减小镜像体积
    rm -rf /usr/local/src/openssl-${OPENSSL_VERSION}* /usr/local/src/openssl-${OPENSSL_VERSION}.tar.gz && \
    echo "OpenSSL 3.x installed and configured successfully."


# 验证 OpenSSL 安装
RUN openssl version

# 修改 xlang 的 CMakeLists.txt
#RUN rm -rf /project/xMind/ThirdParty/xlang/CMakeLists.txt && \
#    cat <<EOL > /project/xMind/ThirdParty/xlang/CMakeLists.txt
## CMakeList.txt : CMake project for X-Lang, include source and define
## project specific logic here.
##
#cmake_minimum_required(VERSION 3.8)
#project("xlang")
#set(CMAKE_CXX_STANDARD 20)
#
## Set output directories
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY \${CMAKE_BINARY_DIR}/bin)
#set(CMAKE_LIBRARY_OUTPUT_DIRECTORY \${CMAKE_BINARY_DIR}/bin)
#set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \${CMAKE_BINARY_DIR}/bin)
#
## 查找 OpenSSL 3.x
#find_package(OpenSSL 3.0 REQUIRED)
#
## To enable Link Time Optimization (LTO) for Release builds.
#if(MSVC)
#    # Enable LTO for MSVC
#    set(CMAKE_CXX_FLAGS_RELEASE "\${CMAKE_CXX_FLAGS_RELEASE} /GL")
#    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "\${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LTCG")
#    set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "\${CMAKE_STATIC_LINKER_FLAGS_RELEASE} /LTCG")
#    set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "\${CMAKE_MODULE_LINKER_FLAGS_RELEASE} /LTCG")
#    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "\${CMAKE_EXE_LINKER_FLAGS_RELEASE} /LTCG")
#elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
#    # Enable LTO for GCC
#    set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -flto")
#    set(CMAKE_EXE_LINKER_FLAGS "\${CMAKE_EXE_LINKER_FLAGS} -flto")
#endif()
#
## 包含 OpenSSL 头文件
#include_directories(\${OPENSSL_INCLUDE_DIR})
#
## 创建并配置 Api 目录
#file(MAKE_DIRECTORY \${CMAKE_BINARY_DIR}/bin/Api)
#configure_file("\${PROJECT_SOURCE_DIR}/Api/value.h" "\${CMAKE_BINARY_DIR}/bin/Api/value.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/value.cpp" "\${CMAKE_BINARY_DIR}/bin/Api/value.cpp")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xhost.h" "\${CMAKE_BINARY_DIR}/bin/Api/xhost.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xlang.h" "\${CMAKE_BINARY_DIR}/bin/Api/xlang.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xload.h" "\${CMAKE_BINARY_DIR}/bin/Api/xload.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xload.cpp" "\${CMAKE_BINARY_DIR}/bin/Api/xload.cpp")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xlstream.h" "\${CMAKE_BINARY_DIR}/bin/Api/xlstream.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xpackage.h" "\${CMAKE_BINARY_DIR}/bin/Api/xpackage.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xport.h" "\${CMAKE_BINARY_DIR}/bin/Api/xport.h")
#configure_file("\${PROJECT_SOURCE_DIR}/Api/xproxy.h" "\${CMAKE_BINARY_DIR}/bin/Api/xproxy.h")
#
## 包含 Api 目录
#include_directories("Api")
#
## 获取源文件
#FILE(GLOB Api_SRC "Api/*.cpp")
#FILE(GLOB AppEntry_SRC "X.cpp" "cli.cpp")
#
## 添加可执行文件
#add_executable(\${PROJECT_NAME}
#    \${Api_SRC}
#    \${AppEntry_SRC}
#)
#
## 链接 pthread, dl 和 OpenSSL
#if(NOT (WIN32))
#    target_link_libraries(\${PROJECT_NAME} pthread dl OpenSSL::SSL OpenSSL::Crypto)
#endif()
#
## 添加子目录
#add_subdirectory("Main")
#add_subdirectory("os")
#add_subdirectory("Http")
#add_subdirectory("PyEng")
#add_subdirectory("DevSrv")
#if(WIN32)
#    add_subdirectory("winner")
#endif()
#add_subdirectory("sqlite")
#add_subdirectory("Image")
#add_subdirectory("WebCore")
#add_subdirectory("all")
#add_subdirectory("Interop")
#add_subdirectory("algorithm")
#if(NOT (BARE_METAL))
#    add_subdirectory("BareLink")
#    add_subdirectory("Yaml")
#endif()
#EOL

#RUN /bin/bash -c "source ~/.bashrc && \
#    cd /project/xMind/out && \
#    cmake -DCMAKE_PREFIX_PATH=${OPENSSL_INSTALL_DIR} .. && \
#    make -j$(nproc) "
#
#
#RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#ENV PATH="/root/.cargo/bin:${PATH}"
#RUN cargo install dora-cli --locked && pip3 install dora-rs

CMD ["/bin/bash"]

