FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y vim wget lsof  curl uuid-dev python3.10 python3.10-distutils python3.10-venv  git && \
    apt-get install -y python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

RUN apt-get update && apt-get install -y curl && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    /root/.cargo/bin/rustup default stable

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustc --version && cargo --version

RUN cargo install dora-cli --locked && \
    pip3 install dora-rs


RUN mkdir -p /project && \
    cd /project && \
    git clone https://github.com/moxin-org/mofa.git && \
    cd mofa && \
    cd /project/mofa/python && \
    pip3 install --upgrade pip --index-url https://pypi.org/simple && \
    pip install --upgrade --ignore-installed blinker && \
    pip3 install uv && uv pip install --system -e . &&  pip3 install -e .


WORKDIR /project

CMD ["/bin/bash"]
